[package]
name = "custom_debug_derive"
version = "0.1.3"
authors = ["panicbit <panicbit.dev@gmail.com>"]
description = "Derive Debug with a custom format per field"
license = "MIT/Apache-2.0"
repository = "https://github.com/panicbit/custom_debug_derive"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
synstructure = "0.10.0"
proc-macro2 = "0.4.19"
syn = "0.15.7"
